services:
  postgres:
    container_name: local-db
    image: postgres:16.3-alpine
    restart: always
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    environment:
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./local_pgdata:/var/lib/postgresql/data
    